name: CI Workflow

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Flask application
        run: |
          nohup python main.py &  # Start Flask app in the background
          sleep 5  # Wait for the app to start

      - name: Run simple test
        run: |
          curl http://127.0.0.1:5000/hello/test > result.txt
          echo "Test result:"
          cat result.txt

      - name: Shut down Flask app
        run: |
          pkill -f 'python main.py'  # Kill Flask app process
